#!/bin/bash

set -uea -o pipefail

DIR="$(dirname $0)/../"
CUSTOM_FLYTE_INTERNAL_IMAGE="$(cat $DIR/jflyte-build/target/docker/image-name)"

if [ -e "$DIR/.env.local" ]; then
    source "$DIR/.env.local"
fi

FLYTE_INTERNAL_IMAGE=${FLYTE_INTERNAL_IMAGE:-$CUSTOM_FLYTE_INTERNAL_IMAGE}

docker run -it \
    --env-file=.env.local \
    -e "FLYTE_INTERNAL_IMAGE=${FLYTE_INTERNAL_IMAGE}" \
    -v "$(pwd):/workdir" \
    -v "$HOME/.config/gcloud/:/root/.config/gcloud:ro" \
    -w "/workdir" \
    --net=host \
    "$FLYTE_INTERNAL_IMAGE" \
    jflyte $*
