name: flytekit-java Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: "0"
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-prepare-release-${{ hashFiles('pom.xml') }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11.0
    - name: Verify with Maven
      run: mvn verify
