name: flytekit-java build

on:
  push:
    branches:  [master]
  pull_request:
    branches:
      - master

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-prepare-release-${{ hashFiles('pom.xml') }}
      - name: Log in to Docker Hub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.FLYTE_BOT_USERNAME }}
          password: ${{ secrets.FLYTE_BOT_PAT }}
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          java-version: 11.0
          distribution: 'adopt'
          server-id: snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Verify with Maven
        if: ${{ github.ref != 'refs/heads/master' }}
        run: mvn --batch-mode verify
      - name: Release snapshot with Maven
        if: ${{ github.ref == 'refs/heads/master' }}
        run: mvn --batch-mode deploy -DpreparationGoals=clean -Ddockerfile.push
        env:
          GITHUB_USERNAME: "${{ secrets.FLYTE_BOT_USERNAME }}"
          GITHUB_TOKEN: "${{ secrets.FLYTE_BOT_PAT }}"
