name: Flytekit Java Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: "0"
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify with Maven
      run: mvn verify
    - name: Build with Maven
      run: mvn package
    - name: Build & Push jflyte Docker Image to Github Registry
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.FLYTE_BOT_USERNAME }}"
        password: "${{ secrets.FLYTE_BOT_PAT }}"
        image_name: ${{ github.repository_owner }}/jflyte
        image_tag: latest,${{ github.sha }},v${{ steps.bump.outputs.version }}
        push_git_tag: false
        push_image_and_stages: false
        registry: ghcr.io
        build_extra_args: "--compress=true"
        context: .
        dockerfile: Dockerfile