name: Run Nexus goal
on:
  workflow_dispatch:
    inputs:
      nexus_goal:
        description: 'Nexus goal to run'
        required: true

jobs:
  run-goal:
    runs-on: ubuntu-latest
    name: Runs nexus goal
    steps:
      - uses: actions/checkout@v2
        with:
          fetch: "0"

      # https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-prepare-release-${{ hashFiles('pom.xml') }}

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.SONATYPE_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Run nexus goal
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SONATYPE_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:${nexus_goal} -DnexusUrl=https://oss.sonatype.org/ -DserverId=ossrh -P release
